### ISSUE TITLE
Find Project Name

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#1]
We need to find a project name, maybe a logo.

**Comment by hwirnsberger** [comment]
Wie wäre es mit:

MoleHome
WildHogAuto
Gardhomation
BoarAut

**Comment by hwirnsberger** [comment]
MoleHome

**Comment by hwirnsberger** [comment]
WildHogAuto

**Comment by hwirnsberger** [comment]
Gardhomation

**Comment by hwirnsberger** [comment]
BoarAut

**Comment by eerofeev** [comment]
Hogarama

**Comment by ErhardSiegl** [comment]
![bigboar](https://cloud.githubusercontent.com/assets/1012746/18598397/c9ac3c50-7c52-11e6-9f6c-414804ca544f.png)

**Comment by ErhardSiegl** [comment]
![little_boar](https://cloud.githubusercontent.com/assets/1012746/18598401/d25b6e84-7c52-11e6-8d99-c769a4371a91.png)

**Comment by AdrianFarmadin** [comment]
Savannah

**Comment by AdrianFarmadin** [comment]
Ranger

**Comment by hwirnsberger** [comment]
Project name is hogarama!
