### ISSUE TITLE
Create Matrix with the skills of the employees

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#103]
To get an overview which skills the employees from Gepardec have a matrix with defined skill should be created.

Skills for example are: AngularJs, Ansible, PO, Riskmanagement, JSF, Openshift ...

**DOD**
- [ ] Skills are defined.
- [ ] every employee adds himself
- [ ] someone checks if it plausible :-D

**Comment by ErhardSiegl** [comment]
Should we move it to Gepardec-Box?

**Comment by cchet** [comment]
I think so too, because is not only worth for hogarama

**Comment by hwirnsberger** [comment]
moved to private repository gepardecbox
