### ISSUE TITLE
Create an Administration Page

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#105]
To check the status of the raspberries there should be an administration page.
Not all users should have access to it so authentication is needed.

**Solution hint**
Use KeyCloak with Google auth 

**DOD**
- [ ] Users can be managed
- [ ] Admin can log in and view some data

**Comment by ErhardSiegl** [comment]
I think we can close this issue since it was opened to showcase Keycloak and SSO is integrated and used. Any objections?
