### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#106]
**As plant owner I want to see the historical data of sensors in order to determine the cause why my plant died during my holidays**

### Acceptance Criteria
- [ ] There exists a web page were the user can select a sensor and a certain time interval and the historical data is shown.
- [ ] Only one value per hour should be picked from the data.
- [ ] Responsetime max 3 sec

**Comment by awagenhoffer** [comment]
Requests take too long:
![request_too_long](https://user-images.githubusercontent.com/17886507/36539419-0ee50fc4-17d7-11e8-83f2-10d0acf78148.png)
Bad performence "where clause" with dates (mongo)?

**Comment by fhochleitner** [comment]
blocked by #162
