### ISSUE TITLE
Plant requests water

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#107]
If a moisture value of a plant drop below a certain value a led should start blinking at the raspberry and an email should be send to notify the user.

**DOD**
- [ ] the led blinks
- [ ] user gets mail

**Comment by fhochleitner** [comment]
Regarding this story and Epic #77 - we should talk about whether we still want to implement this feature as described above, or if we'd rather want to have a flexible rule system that controls the pump with regards to the sensor value automatically. 
Also, in the second case we need to think about a safety net so the pump ignores the signal if there is not enough water left for the pump to be underwater

**Comment by ErhardSiegl** [comment]
As first step a simple hardcoded rule is sufficient. Later we can add a rule system.
Regarding the emergency-stop for not enough water we could do a simple mechanical circuit breaker  as a first step.

**Comment by ErhardSiegl** [comment]
Since we do connect pumps, this issue is obsolete? Replaced by #142?

**Comment by fhochleitner** [comment]
@ErhardSiegl you are right.
I'm closing this issue now as we skipped the led notification and connected pumps instead.
