### ISSUE TITLE
How to assemble Habarama (Raspi + Sensor)

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#117]
As a Hogarama User I want a detailed description on how to assemble a working Habarama so that I can easily monitor my plants at home. 

**Acceptance Criteria** 
- [ ] There exists a documentation in the wiki that describes how to use the circuit layout to connect raspberry to the sensor and pump.

**Comment by fhochleitner** [comment]
We should discuss whether the current documentation is sufficient to close this user story. The thing one could argue isn't sufficiently documented yet is how to connect the sensor/pump to the raspberry pi as there is only an image showing how to connect them without a text description
