### ISSUE TITLE
How are sensor data aggregated in cloud

### ISSUE THREAD

**Issue by AdrianFarmadin** [Gepardec/Hogarama#121]
Current format for hogajama messages is:
```
{
  "sensorName": <sensorName>,
  "type": <sensorType>,
  "value": <value>,
  "location": <location>,
  "version": <version>
}
```

Based on which fields are the data aggregated on server(displayed as one line in graph)?

**Comment by Montecito** [comment]
Currently the sensor name must be unique.
We can discuss a way to implement another mechanism to identify sensors (e.g. by generated uuid at startup) --> plz open a seperate issue for this.
