### ISSUE TITLE
Raspberry PI auth keys

### ISSUE THREAD

**Issue by AdrianFarmadin** [Gepardec/Hogarama#122]
In current ansible set-up script:
* Insert SSH keys from predefined list
* Disallow root SSH access
* Disallow password authentication

If a user (not in predefined auth list) try to install Habarama on his RaspberryPi, then his loose access to the Raspberry.

We need to update ansible script so this doesn't happen.

- [x] add documentation in readme and wiki

**Comment by ludwigSteindl** [comment]
ToDo: 
- Add documentation - explain why one must adapt ssh keys
