### ISSUE TITLE
Graph does not show on iOS

### ISSUE THREAD

**Issue by sjutz** [Gepardec/Hogarama#125]
**Acceptance Criteria**
- [ ] iOS-users can also see the graph

**Comment by AdrianFarmadin** [comment]
### Cause
Translate value of `<g>` tag is wrongly computed in safari browser.

For example:
```
<g class="highcharts-label highcharts-data-label highcharts-data-label-color-0 " transform="translate(0,-9999)">
```

**Comment by Montecito** [comment]
Thx to:
https://stackoverflow.com/questions/45433237/highcharts-not-display-for-ios-and-safari

Last commit (512a314) fixed the issue on iPhone.

Verified with iPhone 7
