### ISSUE TITLE
Timezone JBoss/Records

### ISSUE THREAD

**Issue by awagenhoffer** [Gepardec/Hogarama#129]
**Acceptance Criteria**
- [ ] Correct time is shown on the hogajama charts homepage (EU/Vienna).
- [ ] Raspberries need to be configurable regarding the time zone. 

The records have bad time in the database . (Offset: -1)
![timezonebug](https://user-images.githubusercontent.com/17886507/36540829-1da608f6-17dc-11e8-84f7-c51ff0afb6e7.png)
.

**Comment by fhochleitner** [comment]
See attached image. Issue is resolved in the current version

![Screenshot from 2019-05-10 11-58-28](https://user-images.githubusercontent.com/36953096/57520587-50018200-731e-11e9-908e-a74a46a6d4d2.png)
