### ISSUE TITLE
Water Sensor permanently carries current

### ISSUE THREAD

**Issue by ludwigSteindl** [Gepardec/Hogarama#135]
In the habarama/plant.py main loop, the sleep function needs to be moved to the end of the loop. Otherwise, the sensor is permanently carrying current.

**Comment by ErhardSiegl** [comment]
But the ```time.sleep(waitInterval)``` is at the end of the loop. Did you measure permanent current on the sensor?

**Comment by ludwigSteindl** [comment]
waitInterval is set to 0. sampleInterval is set to 3. Therefore, the algorithm switches on the sensor, waits three seconds, takes a measurement, sends the data to AMQ, switches off the sensor and then directly enters the next iteration without waiting.

**Comment by ErhardSiegl** [comment]
Then the waitInterval should be set to some reasonable value. Maybe it was set to 0 for demo or testing purpose. Permanent current is certainly not good for the sensor.

**Comment by ErhardSiegl** [comment]
@fhochleitner Is this finished with b0a7937 ?

**Comment by fhochleitner** [comment]
yes, this commit adapted the script so that the sensor is not permantly carrying current. atm with a 15s delay for demo purposes. 
the script has also been adapted to return mapped values for our current type of sensors
