### ISSUE TITLE
Add logic to water plants with pump

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#142]
As a User I want my plants to get water when they need it according to their needs so they survive even when I forget about them. 

***Acceptance Criteria***

- [x] There exist rules that state a certain water level at which the Habarama starts pumping water
- [ ] As a first step those rules are hardcoded
- [ ] Habarama sends plant type to server together with sensor information
- [ ] There are at least 2 different plant types defined on server 
- [ ] If water level falls below defined threshold for this plant type the pump gets activated. 

**Solution Hint**
- Client needs to be adapted in order to send the required information. 
- There needs to be a time defined for how long the pump should be active.

**Comment by ErhardSiegl** [comment]
When implementing this issue two problems came up:

1. I wanted to implement the Logic in the domain-layer, but the domain has no access to the HabaramaDAO. So I moved the DAO to the domain project following the dependency inversion principle.
1. Date manipulation with java.util.Date is no fun. I suggest using some Java8 date classes. Suggestions welcome.

**Comment by fhochleitner** [comment]
@ErhardSiegl as I recently came to some information regarding the new DateTimeAPI from java 8 I am more than happy to give input/provide help on friday.
