### ISSUE TITLE
Install RedHat SSO in OpenShift

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#145]
As a developer I want to have Keycloak (RedHat SSO) installed in OpenShift so I can use it for further security configuration. 

** Acceptance Criteria ** 
- [x] Keycloak pod is running on OpenShift
- [x] It is possible to login to our Keycloak instance
- [x] User Login Data is persistent and will not be purged when restarting a pod

**Comment by ErhardSiegl** [comment]
See https://github.com/Gepardec/Hogarama/wiki/Sensors#adding-new-sensor-types
