### ISSUE TITLE
Documentation for actors

### ISSUE THREAD

**Issue by Tharnas** [Gepardec/Hogarama#146]
I created some documentations for actors. As I'm not able to update Wiki pages I created some markdown files [in a branch](https://github.com/Tharnas/Hogarama/tree/actor-documentation/Habarama/client/docs) so you can copy/update it.

I suggest to add the following descriptions in the following locations:
* https://github.com/Tharnas/Hogarama/blob/actor-documentation/Habarama/client/docs/actor.md at Hogarama -> Habarama -> Actor 
* https://github.com/Tharnas/Hogarama/blob/actor-documentation/Habarama/client/docs/gpio-actor.md at Hogarama -> Habarama -> Actor -> GPIO
* https://github.com/Tharnas/Hogarama/blob/actor-documentation/Habarama/client/docs/console-actor.md at Hogarama -> Habarama -> Actor -> Console

And update Hogarama -> Habarama -> Raspberry Pi with https://github.com/Tharnas/Hogarama/blob/actor-documentation/Habarama/client/docs/Raspberry-pi.md

Please let me know in case of an uncertainty.

**Comment by fhochleitner** [comment]
Thank you for your input @Tharnas! We will review it as soon as we start working on this issue and will let you know if we have any questions. Until then: thank you very much for your contribution!!

**Comment by Tharnas** [comment]
Ok, I updated the wiki.
