### ISSUE TITLE
Habarama on a microcontroller

### ISSUE THREAD

**Issue by Tharnas** [Gepardec/Hogarama#148]
As a Hogarama user I want a more lightweight client that is cheaper and consumes less power.

I created a client with Arduino for a microcontroller (ESP8266). I uploaded the code with some documentation here:
[https://github.com/Tharnas/habarama-esp8266](https://github.com/Tharnas/habarama-esp8266)

Let met know what you think about it.

**Comment by ErhardSiegl** [comment]
Thats a real neat and cheep setup. I like it.
 @fhochleitner we should discuss supporting this configuration.
