### ISSUE TITLE
Prevent pump from running dry

### ISSUE THREAD

**Issue by sthausmann** [Gepardec/Hogarama#156]
### Acceptence criteria

- [ ]  It is not possible that the pump breaks because it pumps all water out of the container
- [x] Try out the floater if it works. 

### Solution hint
One solution would be to check water level in tank 
https://www.youtube.com/watch?v=P6QmFsQMz1s
https://www.youtube.com/watch?v=08dcoXZEtqs

Another would be to create a mechanical solution that breaks the circuit if the water level is under a certain threshold.

**Comment by fhochleitner** [comment]
according to our tests on friday the floater works neatly. 
the question that remains whether we are content with our current solution or if we should try out different solutions to prevent "mini-shortcuts" introduced by our current solution when the water that is left in the tube flows back into the tank

**Comment by csalmhof** [comment]
Possible floaters with hardware switch would be something like this:

- https://www.ebay.de/itm/Wasserstandssensor-Horizontale-Flussigkeit-PP-Seitenmontage-Schwimmerschalter/113100332336
- https://www.ebay.de/itm/Schwimmerschalter-Wasserstandssensor-aus-Edelstahl/132632567787
- https://www.ebay.de/itm/Wasserstand-Sensor-Weiss-PP-Rechtwinkliger-Schwimmerschalter-K1C4/282994154325

I think the problem with the "mini-shortcuts" will not be solved with one of these.

**Comment by ErhardSiegl** [comment]
The third one looks compact. I think its good enough. Probably the "flowing back" is not much of a problem in practice.

**Comment by fhochleitner** [comment]
@ErhardSiegl is our self-made floater enough to close this issue or should we try out smaller solutions as proposed by @csalmhof ?
