### ISSUE TITLE
Configure Keycloak to authenticate with Google

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#158]
As a user I want to use my Google credentials to authenticate with Hogarama.

**Acceptance Criteria**

- I can authenticate myself to Hogarama with my Google credentials.

**Comment by cchet** [comment]
Where is Keycloak located, because I couldn't find any template in the sources as well as no service on the Openshift Projects ? 
I could provide a Keycloak template if needed.

**Comment by ErhardSiegl** [comment]
The templates are in Hogarama/Templates/sso
