### ISSUE TITLE
Configure simple security-Domain with fixed users and admin-group in elytron subsystem

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#160]
Part of #105 

**Acceptance Criteria**

- [x] I am able to create users in Keycloak and add different rights to the users (admin, user privileges)
- [x] I can authenticate a user on jboss with users added in keycloak

**Comment by eerofeev** [comment]
We can't connect RH SSO 7.1 with EAP 7.1 via Elythron. Elythron adapter is provided since SSO 7.2
So old good Security-Subsystem is used.
