### ISSUE TITLE
Configure JBoss on Openshift

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#165]
As a developer I want to configure our JBoss on Openshift so that I can easily set the parameters for context-path, security etc.

**Acceptance Criteria**
- [ ] strategy how to configure JBoss on Openshift is defined
- [ ] JBoss on Openshift is configured as defined in the strategy

**Tasks**
- [ ]

**Comment by sjutz** [comment]
Currently we use Hogarama/Hogajama/configuration/standalone-openshift.xml
