### ISSUE TITLE
Use service name instead of hardcoded URLs

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#166]
**User Story**

As an architect, I want the service name to be used instead of hardcoded URLs. However, there should be a fallback URL pointing to a local OpenShift instance in case the service name environmental variable is not set.

**Comment by ErhardSiegl** [comment]
Right now we have:
```
    MqttClient mqttClient = new MqttClient().
      withHost(Optional.ofNullable(System.getenv("AMQ_HOST")).orElse("https://broker-amq-mqtt-ssl-57-hogarama.cloud.itandtel.at")).
```
If AMQ_HOST is not configured, it uses the AMQ-Broker on out test-environment. However it should use the AMQ on the local OpenShift instance. This is represented by the service name (= hostname).
