### ISSUE TITLE
Implement scheduler for pump activation

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#168]
**User Story**
As a Product Owner, I want the water level to be verified on a regular basis. 

**Acceptance Criteria**

**Tasks**

**Questions that need to be answered**
- [ ] How should we implement the scheduler in order to be consistent with the currently implemented rule which already has a measuring interval defined?!
- [ ] Do we really need the measuring interval to be defined in the wateringStrategy?

**Comment by fhochleitner** [comment]
@ErhardSiegl during the sprint planning we had several questions regarding your wish for a scheduler to be implemented. We think it is best to discuss these so we are able to adequately estimate this issue. We will try to achieve this until next friday.

**Comment by ErhardSiegl** [comment]
As discussed the following logic is implemented: The WateringStrategy gets all sensor-data within the last 60 Minutes. If the average is below 0.2, the pump is activated fo 5 Seconds. So it is not really important how often the scheduler starts.
