### ISSUE TITLE
Hogajama docker image is too big

### ISSUE THREAD

**Issue by AdrianFarmadin** [Gepardec/Hogarama#17]
Hogajama docker image is too big. It's 801.1 MB. That is really a lot :) 

Please take a closer look if it can be smaller.

**Comment by eerofeev** [comment]
Even if we build it on basis of wildfly image, the resulting image is big as well, even if our layer is very small.

**Comment by WernerGepardec** [comment]
smaller image pushed to gepardec/hogajama

**Comment by AdrianFarmadin** [comment]
The point is to reuse already available layers. This way users don't need
to redownload all layers if we make a change in our image.

Why to reinvent a wheel when we already got one. :)

Am 16.12.2016 1:08 Nachm. schrieb "eerofeev" <notifications@github.com>:

Even if we build it on basis of wildfly image, the resulting image is big
as well, even if our layer is very small.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gepardec/Hogarama/issues/17#issuecomment-267581106>,
or mute
the thread
