### ISSUE TITLE
Ansible script fails when private key is protected by passphrase

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#172]
When running the ansible setup script for habaramas the setup fails when the option to setup ssh is enabled and the ssh private key is protected by a passphrase

**Comment by ErhardSiegl** [comment]
Is this a bug? I see this more as a feature request.

**Comment by fhochleitner** [comment]
back in the day we have decided that we don't want to support passphrase protected private keys at the moment. 
closing this bug now. if this feature is requested in the future a proper issue should be opened
