### ISSUE TITLE
Bug: Faulty Sensor Data

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#173]
You know what to do

**Comment by ErhardSiegl** [comment]
I don't know what to do. Please describe.

**Comment by fhochleitner** [comment]
This was a reminder ticket for ludwig and myself to investigate the volatile sensor-data of our bought sensors. 
If I remember correctly this issue can be closed due to our use of DIY-sensory. 
@ludwigSteindl correct me if I'm wrong and if not could you close the issue please?
