### ISSUE TITLE
Display watering of plants on homepage

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#178]
As as User I want to know when my plant my watered and how it affected its moisture level.

**Acceptance Criteria**

- [x] Whenever the ActorService is fired it will be logged in MongoDB
- [x] The Homepage shows data points when the plants have been watered
- [x] It is also shown how long the plant has been watered

**Comment by Ruhsi** [comment]
The watering of the plants is now displayed on the homepage. Small waterdrops are displayed and the duration is shown in the label. This looks like the following:
![grafik](https://user-images.githubusercontent.com/24733670/45999686-a6c78d80-c0a6-11e8-92cd-9f4d2bf0b727.png)

However, there are a few issues with this solution:

1. I created a class WateringData, (like SensorData), which holds the specific watering data. maybe WateringData and SensorData should extend an abstract base class. So methods, like ...
`public List<SensorData> getAllData(Integer maxNumber, String sensorName, Date from, Date to)`
don't get copied for every data class, but are more generic.

2. The MongoDbProducer lets you only work with one single collection ('habarama'). So SensorData- and WateringData-objects are all in the same collection in the mongoDB.

3. With the `sendActorMessage(String location, String actorName, Integer duration)` I don't get the current moisture value. So in the frontend I use the previous value (last value before watering) and not the actual.

The code can be reviewed and tested on the branch: **178_Display_watering_of_plants_on_homepage**
