### ISSUE TITLE
DynDNS

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#18]
If the AWS instance is terminated or ?stoped? the public ip changes.
So to reach *.hogarama.gepardec.com you have to configure the public ip on easyname.
Another aproach is to use dyndns. So the aws instance notifies the dns provider to change the public ip.

**Comment by WernerGepardec** [comment]
NoIp: http://noip.com/
Tutorial:
https://www.howtoforge.com/how-to-install-no-ip2-on-ubuntu-12.04-lts-in-order-to-host-servers-on-a-dynamic-ip-address

**Comment by WernerGepardec** [comment]
hogarama.ddns.net
