### ISSUE TITLE
sso yaml file are checked in as binary

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#182]
the following files in Templates/sso are checked in as binary file, but should be ordinary text files:
```
sso-app-secret.yaml
sso-service-account.yaml
sso.yaml
```

**Comment by ErhardSiegl** [comment]
To find binary files you can use the following:
```
diff <(git grep -Ic '') <(git grep -c '') | grep '^>' | cut -d : -f 1 | cut -d ' ' -f 2-
```

**Comment by fhochleitner** [comment]
i have verified that only images, jar files and keystore files are checked in as binaries anymore. 
therefore, im closing this issue
