### ISSUE TITLE
Wrong file path in "Local OpenShift with oc cluster up" wiki page

### ISSUE THREAD

**Issue by Tharnas** [Gepardec/Hogarama#184]
The path for "startAll.sh", "startAll.cmd", "remote-insert-data.sh" and "s2i_hogajama.sh" is wrong. It should be located in folder "Templates" instead of "template".

![image](https://user-images.githubusercontent.com/8459274/46903879-2db89a80-cedc-11e8-99d2-d65662c55387.png)

![image](https://user-images.githubusercontent.com/8459274/46903905-8c7e1400-cedc-11e8-9125-bff3e78e43c0.png)

Link to wiki page: [Local OpenShift with oc cluster up](https://github.com/Gepardec/Hogarama/wiki/Local-OpenShift-with-oc-cluster-up)

**Comment by Tharnas** [comment]
I updated the wiki page. Should be ok now.

**Comment by fhochleitner** [comment]
thank you for your keen eyes and updating the wiki page @Tharnas
