### ISSUE TITLE
Assign sensor to user

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#203]
As a product owner I want the sensors and pumps to be assigned to a certain user so that Hogarama can provide user-specific data and actions.

**Acceptance Criteria**
- [ ] Database stores assignment of sensors / pumps to user
- [ ] Sensors / pumps can be registered for a certain user

**Tasks**
- [ ] ...

**Comment by ludwigSteindl** [comment]
Blocks #204
