### ISSUE TITLE
Display all sensors of one user

### ISSUE THREAD

**Issue by SabrinaPloner** [Gepardec/Hogarama#204]
As a user I want to have an overview of all my plants and their status so that I can monitor my plants.

**Acceptance Criteria**
- [ ] Web Service exists delivering sensor data for all plants for one user
- [ ] GUI displays the sensor data for all plants of one user
- [ ] Secured access

**Tasks**
- [ ] ...

**Comment by ludwigSteindl** [comment]
Blocked by #203
