### ISSUE TITLE
Admin Page UX Design

### ISSUE THREAD

**Issue by csalmhof** [Gepardec/Hogarama#207]
As a user I want to have a good user experience for this tasks:

- [ ] Landing Page
- [x] Login/Registration/Forgot password
- [x] Dashboard (what should be shown? Notifications? TODO: discuss with PO)
- [x] Show all sensors (List, Details)
- [x] Add new sensors [name, place, id] (discuss with PO how new sensors should be added)
- [ ] Edit sensors
- [ ] User settings

**Comment by mk-gepard** [comment]
@MauriceNino here is the url to prototype. 
https://sketch.cloud/s/ng344/a/MAaWy3/play
