### ISSUE TITLE
Can not build Hogajama   "Internal error in the mapping processor: java.lang.NoClassDefFoundError"

### ISSUE THREAD

**Issue by johannesr124** [Gepardec/Hogarama#222]
Hogajama fails to build at "Hogajama-rs"
- Java:      openjdk version "11.0.3"
- Maven:   version "Apache Maven 3.5.4"
- OS:        Fedora 30, Kernel 5.0.17-300

Error:
` /home/jriegler/git/Hogarama/Hogajama/hogajama-rs/src/main/java/com/gepardec/hogarama/rest/mapper/SensorMapper.java:[11,8] Internal error in the mapping processor: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBElement`

**Comment by fhochleitner** [comment]
you have to use jdk version 8. Hogarama is not compatible with java version higher than 8
