### ISSUE TITLE
Hogajama compatibility java 11

### ISSUE THREAD

**Issue by johannesr124** [Gepardec/Hogarama#223]
Making Hogajama compatible for Java Version 11.

-How
Update "org.mapstruct.version" to latest Version --> 1.3.0

**Comment by fhochleitner** [comment]
can you verify, that thhe latest version of mapstruct is also compatible with jdk 8? if not, we will also have to upgrade our jboss version to 7.2 as version 7.1 (currently in use) does not support jdk 11. 

source: https://access.redhat.com/articles/2026253#EAP_71

**Comment by johannesr124** [comment]
I tried building with mapstruct version 1.2.0 and java 11, works fine.
Version 1.2.0 of mapstruct is compatible with jdk 8.
http://mapstruct.org/news/2017-10-18-mapstruct-1_2_0_Final-is-out/
http://mapstruct.org/documentation/1.2/reference/html/

**Comment by ErhardSiegl** [comment]
@johannesr124 Is this done?

**Comment by johannesr124** [comment]
It was done, probably there are new complications in our project with java 11 since then.
