### ISSUE TITLE
Display Charts for Habarama Uptime

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#23]

**Comment by hwirnsberger** [comment]
do we need that? Sensor data are already displayed.

**Comment by Montecito** [comment]
Is the uptime of a Habarama included in this data?

I think this issue related to a different type of data (uptime), that is not yet send to AMQ/Mongodb

**Comment by hwirnsberger** [comment]
@ErhardSiegl Do we need it or not?

**Comment by ErhardSiegl** [comment]
No
