### ISSUE TITLE
Give Jenkins right to start pods,...

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#24]
Need cluster admin. What do we do exactly?

**Comment by hwirnsberger** [comment]
didnt we agree to have a nightly test at first? and when we need that feature to care about it? so close it for now?

**Comment by Montecito** [comment]
We wanted to create a daily job first (#39),
but the ultimate goal should be that jenkins starts tests automatically after a push to the repo.

Therefore I would leave it open and work on it after #39 is closed.

**Comment by cchet** [comment]
We are doing it in the Liwest project, where the Jenkins isntance is allowed to start slave pods which perform the actual build or execute a specific test suite.

We are allowed to set roles to service account where we set the role edit to the jenkins user.

**Comment by cchet** [comment]
![linux-liwest-cloud-service-account](https://user-images.githubusercontent.com/2004943/32837628-8bc7c976-ca0e-11e7-9a50-c5d15263705e.png)
