### ISSUE TITLE
Stopping and Starting master and nodes does not work. Openshift4 is not responding.

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#257]
Apparently due to a certificate-problem restart of nodes doesn't work. We need it in order to lower costs.

**Comment by ckaserer** [comment]
We are assuming a certificate issue. OpenShift documentation to recover from expired control plane certificates will be tested once the issue can be recreated. 

[https://docs.openshift.com/container-platform/4.2/backup_and_restore/disaster_recovery/scenario-3-expired-certs.html](https://docs.openshift.com/container-platform/4.2/backup_and_restore/disaster_recovery/scenario-3-expired-certs.html)

Recreated OpenShift 4.2. cluster on AWS. Once verified that it is up and running, we will shut it down for a week and check if we can bring it back up after the certificate has expired.

**Comment by ckaserer** [comment]
https://blog.openshift.com/enabling-openshift-4-clusters-to-stop-and-resume-cluster-vms/

**Comment by ckaserer** [comment]
Fixed, scripted and documented: https://github.com/Gepardec/openshift-aws
