### ISSUE TITLE
No Queues are configured on AMQ with local installation

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#276]
With local templates the queues 
```
		<address name="habarama">
			<multicast>
				<queue name="fluentd"/>
				<queue name="watering"/>
			</multicast>
		</address>
```
are not configured anymore.
It seem that the correct broker.xml was deleted in commit 32cb1abeedd15ca286308dc93b7c441a85ed8daa

**Comment by ErhardSiegl** [comment]
@fhochleitner can you explain the commit 32cb1ab? The broker.xml is needed for the S2I build for AMQ.

**Comment by fhochleitner** [comment]
@ErhardSiegl at the time it looked like only AMQ72 was configured anymore and that the old AMQ/configuration directory was not used anymore. I have reverted the changes and restored the deleted file.
