### ISSUE TITLE
Create OpenShift template for Hogarama build and runtime

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#28]
If we make a GIT-branch we might need a new development infrastructure.

**Comment by Montecito** [comment]
We discussed this issue during Horama Retrospective with following output for runtime templates:
https://drive.google.com/drive/u/0/folders/0B66A_9SsiaHlZjIzUGpza2d4UW8

**Comment by Montecito** [comment]
Fixed by 227ed1f, c.f. #35
