### ISSUE TITLE
Verknüpfung "altes Sensordatenformat" mit neuen DB-Strukturen und Prometheus-Labels

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#284]
- Use sensor name from old format as "ID"
- Implement mapping from old format for the sensor service
- Use names that are created in the new GUI (NOT Sensor names) as labels in prometheus.
- Use only device ID and value from sensor data

**Notes:**
Prometheus: 
- unit.name
- sensor.deviceId
- sensor.name

When normalizing (in WateringMDB):
- get sensor-type from database

Implement cache for performance reasons. Invalidate cache when sensor-data changes.

Don't do: change getAllSensorNames() which is used from old GUI.

**Comment by mhofmann-gepardec** [comment]
Blocked by #286
