### ISSUE TITLE
Sensoren "Grüner Gepard", "DIY1" (?), migrieren.

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#291]
Create records in the database via the UI (Debugger) for the exising sensors using sensor name from sensor data from device ID.

**Comment by mhofmann-gepardec** [comment]
@ErhardSiegl please provide more information

**Comment by ErhardSiegl** [comment]
We have one Raspi with two sensors ("Grüner Gepard", "DIY1") in the Vienna office. These two sensors should be inserted into the new sensor configuration database in order to see them in the new GUI.

**Comment by ErhardSiegl** [comment]
Two sensors created. Are loaded into cache and used.
