### ISSUE TITLE
Buy initial hardware

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#3]
Which hardware do we need to get started?

**Comment by AdrianFarmadin** [comment]
Raspberry Pi 3
Power supply 5V micro-USB at least 2.5A
Micro SD card at least 8GB 
Moisture Sensor

**Comment by ErhardSiegl** [comment]
Raspberry Pi:
http://www.pollin.de/shop/dt/OTQxNzkyOTk-/Bauelemente_Bauteile/Entwicklerboards/Raspberry_Pi/Raspberry_Pi_3_Model_B.html

Für die Stromversorgung von mehreren Pi:
http://www.pollin.de/shop/dt/NjE5NzcyOTk-/Computer_Informationstechnik/USB_Technik/USB_Hubs/USB_Hub_LOGILINK_Smile_blau.html
http://www.pollin.de/shop/dt/NTE3ODQ2OTk-/Stromversorgung/Ladegeraete/USB_Ladegeraete/Dual_USB_Ladeadapter_QUATPOWER_PUL5_2_1A_DS_schwarz.html
http://www.pollin.de/shop/dt/OTU3NzcyOTk-/Computer_Informationstechnik/USB_Technik/USB_Adapter/USB_Adapterkabel_USB_A_Micro_USB.html

Speicherkarte:
http://www.pollin.de/shop/dt/NDczNjcyOTk-/Computer_Informationstechnik/Speichermedien/microSD_SDHC_Speicherkarten/MicroSDHC_Card_KINGSTON_SDCA10_UHS_I_10_16_GB.html

**Comment by AdrianFarmadin** [comment]
Moisture Sensor:
https://www.aliexpress.com/item/Smart-Electronics-Soil-Moisture-Hygrometer-Detection-Humidity-Sensor-Module-For-arduino-Development-Board-DIY-Robot-Smart/32328189936.html?spm=2114.01010208.3.2.fhQFQW&ws_ab_test=searchweb201556_8,searchweb201602_3_10057_10056_10065_10068_10055_10054_10069_10059_10058_10073_10017_10070_10060_10061_10052_10062_10053_10050_10051,searchweb201603_4&btsid=c960f9bf-9e0b-4c8d-bdb7-83483381a4be

**Comment by AdrianFarmadin** [comment]
Wird vielleicht für die Stromversorgung so etwas besser sein? 
https://www.alza.de/premiumcord-7-port-d235980.htm?o=8
