### ISSUE TITLE
Peristaltic pump controlled by Raspberry Pi 3

### ISSUE THREAD

**Issue by b0x1** [Gepardec/Hogarama#30]
Klemens has the idea of adding a water pump (cf. https://www.amazon.de/gp/product/B00VPXF10U/) to Hogarama that can be controlled by Raspberry Pi 3. The implementation would be rather straightforward: The pump is soldered to the 5V pin of Raspberry (cf. https://www.amazon.de/forum/-/Tx1ABKMJ790UDOC/) and switched on/off by the presence of electric current. 

A problem we have now is that Amazon does not ship the referenced product to Austria. Alternative: Aliexpress (https://www.aliexpress.com/item/Kamoer-metering-pump-dosing-pump-for-water-milk/2045297039.html), where the shipping will take weeks (or possibly months).

**Comment by mbrandm** [comment]
The idea is to realize the connection to the pump in Java (also the to the moisture measurement). It has to be determined whether this way is possible with the Analog-Digital-Converter MCP3008.

**Comment by b0x1** [comment]
@kwimmergit is magnificient!
