### ISSUE TITLE
Setup Hogarama Project locally with Workaround

### ISSUE THREAD

**Issue by mhofmann-gepardec** [Gepardec/Hogarama#315]
Setup of the Hogarama project locally, so that working on the project can be started.

- Setup IntelliJ
- Get familiar with Hogarama
- Setup project with Workaround (+ Documentation)

**Comment by philzelinger** [comment]
Doku fertig. https://github.com/Gepardec/Hogarama/wiki/Local-JBoss-Development
Neues lokales Setup bei Patrick und Johannes eingerichtet. Funktioniert nach ein paar Problemen, auch dort.
@ErhardSiegl sollen wir jetzt aufgrund diesem Task noch die andere variante über aws remote evaluieren?

**Comment by ErhardSiegl** [comment]
👍Doku. Wenn alle aktuell arbeiten können, hat es keine hohe Priorität.

**Comment by philzelinger** [comment]
Ich verschiebe den task mal in testing, wenn sich nächsten freitag jemand findet, bei dem wir das noch ausprobieren, können wir das gerne machen, ansonsten würde ich den task dann schließen.
