### ISSUE TITLE
Create/Update Domain Model

### ISSUE THREAD

**Issue by mhofmann-gepardec** [Gepardec/Hogarama#322]
System Diagram (Kontextdiagramm)
Datenflussdiagramm

https://docs.google.com/presentation/d/1FqYlPSU49KaEZ3zUxZPyzxM_9c0IYlpz6_o9eszZaI4/edit#slide=id.g75b68c2308_0_0

**Comment by ErhardSiegl** [comment]
Eventuell mit den Tutoren von "Technische Dokumentation & Kommunikation" diskutieren. Input von @csalmhof ?
