### ISSUE TITLE
Hardware buy list

### ISSUE THREAD

**Issue by AdrianFarmadin** [Gepardec/Hogarama#33]
- [x] breadboard wires (Linz: 1 pack, Wien: 1 pack)
- [x] optocoupler (Linz: 1, Wien: 1)
- [x] breadboard (Linz: 2)
- [x] Analog digital convertor (Linz 1, Wien: 1)
- [x] LEDs (+ resistors ?)
- [x] USB-cable (2m, as power supply) (Linz 2)
- [x] USB to ? (Linz: 1, Wien: 2)

**Comment by hwirnsberger** [comment]
Bitte Bestellung vorbereiten und von Erhard prüfen lassen

**Comment by mbrandm** [comment]
Bitte auch die Doppelweibchen-Adapter mitbestellen für das Zusammenstecken der Pins mit den Kabeln.

**Comment by ErhardSiegl** [comment]
Bestellt
