### ISSUE TITLE
On ITandTel OpenShift Cluster Builds for fluentd and amq are broken

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#335]
Currently our builds for fluentd and amq on itandtel openshift instance are broken due to "invalid context directory" error. 

For local deployment this issue has already been fixed with PR 334 (https://github.com/Gepardec/Hogarama/pull/334). Now these changes need to be propagated to the OpenShift Cluster.

**Comment by philzelinger** [comment]
Config in Openshift angepasst 
![image](https://user-images.githubusercontent.com/57404963/83248547-83bb7e00-a1a5-11ea-9236-f790cadd0492.png)
![image](https://user-images.githubusercontent.com/57404963/83248606-9cc42f00-a1a5-11ea-983d-5d761bf02e39.png)
Builds erfolgreich

**Comment by philzelinger** [comment]
@fhochleitner einmal drüber schauen und wenns für dich passt, auf done ziehen
