### ISSUE TITLE
Create Blog Article or Case Study

### ISSUE THREAD

**Issue by mhofmann-gepardec** [Gepardec/Hogarama#351]
Create a  Blog article or a case study for our gepardec website.

Containing the following points:

- Initial Situation
- Objectives
- Solution
- Used Technologies 

Examples:
- Case Studie: https://www.gepardec.com/case-study/hogarama/
- Blog article: https://www.gepardec.com/keycloak/

**Comment by ErhardSiegl** [comment]
https://www.gepardec.com/hogarama-und-the-second-system-effect/
