### ISSUE TITLE
[BUG] calling /rest/sensor/allData Endpoints returns Response Code 500 

### ISSUE THREAD

**Issue by fhochleitner** [Gepardec/Hogarama#385]
Calling the /rest/sensor/allData Endpoints leads to http response code 500 caused by NPE exception

**Comment by ErhardSiegl** [comment]
Please provide more info. e.g: Exception, how did you call the endpoint.

**Comment by fwagner94** [comment]
You have to use `/sensor/allData?onlyDataFromToday=true` because `onlyDataFromToday` is a required parameter.

Does it solve the issue?

**Comment by ErhardSiegl** [comment]
Ich würde den Parameter optional und default auf true setzen.
