### ISSUE TITLE
Angular frontend refactoring

### ISSUE THREAD

**Issue by fwagner94** [Gepardec/Hogarama#414]
**Verbesserungsvorschläge für das Angular Frontend**
- [x] Angular/Ionic auf den neusten Stand bringen
- [x] `log.console(...)` ohne Beschreibung entweder entfernen oder mit einer eindeutigen Beschreibung versehen
- [x] `presentToast` im Fehlerfall verwenden, um eine detailierte Fehlermeldung anzuzeigen

**Comment by ErhardSiegl** [comment]
Die Angular-Issues in https://github.com/Gepardec/Hogarama/security/dependabot sollten behoben werden.
