### ISSUE TITLE
Keycloak Configuration hardcoded

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#433]
unabhängig von dem PR, es schmerzt immer noch, dass die Keycloak Configuration hardcoded ist =/

_Originally posted by @fhochleitner in https://github.com/Gepardec/Hogarama/pull/431#discussion_r872227251_

**Comment by fwagner94** [comment]
TODO: add following parameters as env variables to hogajama in OCP:

- [ ]  KEYCLOAK_REALM
- [ ]  KEYCLOAK_CLIENT_ID
- [ ]  KEYCLOAK_CREDENTIALS_SECRET
