### ISSUE TITLE
Tests with Bash Scripts

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#44]
Why using bash scripts? 
We can create JUnit tests. Even the generation of the "test client" should be possible.

**Comment by hwirnsberger** [comment]
@sjutz https://github.com/Gepardec/Hogarama/wiki/Jenkins

**Comment by sjutz** [comment]
In the Retrospective we decided that we want a quick test of the REST services for the minimal version. Therefore I think bash scripts are well suited for this. However, for future versions I agree that we should think about JUnit tests.
