### ISSUE TITLE
Development and Deployment Process

### ISSUE THREAD

**Issue by steirer2** [Gepardec/Hogarama#45]
1. Developer creates new software version and informs operator
2. Operator updates his test stage (project) 
3. Operator executes his automatic tests & reports bugs
4. Operator executes his manual tests & reports bugs
5. If blocking bugs exist => goto step 1.
6. Operator initiates rolling update to production system
7. Operator executes his tests
8. If blocking bugs exists => rollback.

**Comment by ErhardSiegl** [comment]
Why is here an operator involved? This should be a CI or continuous-deployment-pipeline?

**Comment by hwirnsberger** [comment]
maybe a duplicate with #113 close this issue?

**Comment by ErhardSiegl** [comment]
No answers to questions, closing.
