### ISSUE TITLE
CDK, Development, Deployment Process

### ISSUE THREAD

**Issue by ChrisKofler** [Gepardec/Hogarama#46]
Goal: Create a demo guide in the wiki which describes the complete setup & deployment process starting with the CDK and finishing with the deployment on a public cloud.

1. Developer navigates to https://github.com/Gepardec/Hogarama/wiki --> Setup Guide
2. Developer installs CDK 
3. Developer checks out Hogarama Git Project
4. Developer creates local Hogarama OpenShift project  & checks if it's running
5. Developer puts in sample data 
-----

1. Developer changes code locally
2. CDK builds new version using the locally changed code
3. Developer tests new version locally 
4. Developer checks-in code into his own GitHub Account, project "MyHogarama"

Deployment steps to public provider
1. Developer gets OpenShift voucher from ITandTel
2. Developer sets up account at his OpenShift provider (e.g. ITandTel). 
3. Developer sets up the MyHogarama project using the code from his GitHub Account

 

Motivation
- customer who want to use OpenShift on premise instead of the public cloud
- customers who want to have the development offline on their machines

**Comment by sjutz** [comment]
In order to develop locally, one can either use a local JBoss, deploy Hogajama there and port-forward to the pods required, eg mongodb. The other option is to use template/local_openshift/s2i_hogajama.sh which builds and pushes a new image from the local source.
