### ISSUE TITLE
create possibility to control pump via raspi

### ISSUE THREAD

**Issue by mbrandm** [Gepardec/Hogarama#51]
For controling the pump, which is connected to raspberry pi, a possibility should be created to manage the pump. First a mqtt-client will be provided on the raspberry, after that the control on open shift will be created.

**Comment by b0x1** [comment]
RasPi can be controlled via AMQ, see commit [#9b5c73ca6c54b7d0eff39e0df68d39f6fa9fd51f](https://github.com/Gepardec/Hogarama/commit/9b5c73ca6c54b7d0eff39e0df68d39f6fa9fd51f)
