### ISSUE TITLE
1024 Scaling: Auto scale the number of JBoss pods depending on number of users

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#55]
When more users are connected to Hogarama the number of WildFly-pods should increase.
E.g:
1 user: 1 pod
2 users: 2 pods
4: 3
8: 4
Optional: Downscale after a few minutes

**Comment by Montecito** [comment]
We should have a look at:
https://fabric8.io/guide/javaLibraries.html
https://github.com/fabric8io/kubernetes-client
https://github.com/openshift/openshift-restclient-java

**Comment by ErhardSiegl** [comment]
Get the active sessions with `curl http://localhost:8080/ScalingTest`

**Comment by Montecito** [comment]
Implemented scale up.

Hogajama must now be configured with an additional ENV variable OPENSHIFT_AUTH_TOKEN.

Needs testing on ITandTEL ;-)

**Comment by sjutz** [comment]
Tested on ITandTEL in a new project created from template.

**Comment by hwirnsberger** [comment]
tested. scale up is after 3 sessions.
