### ISSUE TITLE
1024 Scaling: Simple URL for GUI

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#56]
Provide a simple URL to connect to existing Hogajama charts. (Production)
Provide a simple URL to connect to new Hogajama charts instance. (Test)
Optional: Display QR-Code for the page. The QR-Code should be displayed on the charts page (bottom left) an represent the URL of the charts page.

**Comment by Montecito** [comment]
QR code implemented in #67

**Comment by Montecito** [comment]
Would something like:

https://tinyurl.com/hogarama-dev

be sufficient?

**Comment by ErhardSiegl** [comment]
Yes, should be good enough.

**Comment by Montecito** [comment]
Can I close this issue?

**Comment by Montecito** [comment]
C.f. https://github.com/Gepardec/Hogarama/wiki/PresentationUsecases
