### ISSUE TITLE
1024 Vorstellung: Mobile display optimisation

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#58]
Chart page should look OK on mobile devices.

**Comment by Montecito** [comment]
First scatch:

![2017-08-25_hogarama_mobileoptimization](https://user-images.githubusercontent.com/1809686/29958688-48012b2e-8ef4-11e7-8933-d1b97ffba7fa.png)

**Comment by hwirnsberger** [comment]
The scatch is for the desktop browser.
QR Code should not be shown on mobile devices.
Add Tiny Url to Page when in development stage.
Add favorite icon gepardec style. currently is the angular logo
