### ISSUE TITLE
1024 Staging: Build several Hogarama instances with one command

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#60]
something like:
`make-hogarama tiger lion cheetah`
should create threee fully functional instances of Hogarama.

**Comment by sjutz** [comment]
Create projects manually
Run script `$HOGARAMA_HOME/template/make-hogarama.sh <instance-name1> <instance-name2> <...>`, for example `$HOGARAMA_HOME/template/make-hogarama.sh lion tiger`
