### ISSUE TITLE
AMQ or MQTT accept data only in form: {\"message\"=>3.5}"

### ISSUE THREAD

**Issue by AdrianFarmadin** [Gepardec/Hogarama#64]
AMQ or MQTT accept data only in form: `{\"message\"=>3.5}"`

The data should be in following form:
```
{
  "sensorName": <sensorName>,
  "type": <sensorType>,
  "value": <value>,
  "location": <location>,
  "version": <version>
}
```

**Comment by b0x1** [comment]
Doesn't the AMQ server accept strings of any form?

**Comment by Montecito** [comment]
It actually should and does as far as I know..

**Comment by AdrianFarmadin** [comment]
I sent wrong formatted message: `{"sensorName": PflanzeWien, "type": "water", "value": 123, "location": "Wien", "version": 1 }`

it should be: `{"sensorName": "PflanzeWien", "type": "water", "value": 123, "location": "Wien", "version": 1 }`
