### ISSUE TITLE
Protocol for Raspi to Cloud Communication (JSON)

### ISSUE THREAD

**Issue by b0x1** [Gepardec/Hogarama#66]
We need to standardise the string format for the messaging between Raspi and the Cloud for

- sensor data
- pump control message

**Comment by ErhardSiegl** [comment]
The sensor data is defined with Swagger in ./Hogajama/hogajama-interfaces/src/main/swagger/hogajama.swagger.yaml
See also https://github.com/Gepardec/Hogarama/wiki/Interfaces
