### ISSUE TITLE
1024 Vorstellen: Generate QR Code on sensor statistics page

### ISSUE THREAD

**Issue by Montecito** [Gepardec/Hogarama#67]
The Habarama charts page should show a QR-code with page address embedded.

E.g.:
https://hogajama-57-hogarama.cloud.itandtel.at/hogajama-charts.html
is the URL of our production stage and this URL should be encoded in QR and displayed on the page.

**Comment by mbrandm** [comment]
You can see how it works on http://localhost:8080/index3.html

**Comment by Montecito** [comment]
Copied sample from index3.html to hogajama-charts.html
