### ISSUE TITLE
Bug in hogajama-charts.html when no sensor data is available

### ISSUE THREAD

**Issue by sjutz** [Gepardec/Hogarama#68]
When a new project is created using the template hogarama_template_with_routes.yaml, the sensor data presentation page (frontend) is stuck because there is no data in the database.
![screenshot](https://user-images.githubusercontent.com/11520909/28961495-c6710c02-7902-11e7-9b8a-5d7e2cac6808.png)

**Comment by Montecito** [comment]
Fixed, needs to be tested :-)

**Comment by sjutz** [comment]
Tested =)
