### ISSUE TITLE
Charts image not displayed on mobile phone

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#69]
The charts image on the charts-page is not displayed on my Galaxy S3, Android 4.3.

**Comment by awagenhoffer** [comment]
Browser | Version | Test | Mobile OS | Note
------------ | ------------- | ------------- | ------------- | ------------- 
Firefox | 55.0.2 | OK | Android 6.0 |  
Opera | 42.9.2246.119945 | OK | Android 6.0 |  
Dolphin Browser | 12.0.2 | OK | Android 6.0 |  
CM Browser | 5.21.17 | OK | Android 6.0 |  
Safari | ? | OK | IOS |  
Chrome | 60.0.3112.116 | OK | Android 6.0 |  
UC Browser | 11.4.5.1005 | NOK | Android 6.0 | Graphic is not displayed
