### ISSUE TITLE
Aggregate Container Logs with EFK Stack

### ISSUE THREAD

**Issue by steirer2** [Gepardec/Hogarama#70]
Goal: have a central view for container logs. Otherwise troubleshooting will be hell when running multiple containers.

https://docs.openshift.com/enterprise/3.1/install_config/aggregate_logging.html

**Comment by hwirnsberger** [comment]
Do you mean for example:
https://logging.cloud.itandtel.at/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1w,mode:relative,to:now))&_a=(columns:!(kubernetes.container_name,message),index:'project.57-hogarama.99b7c383-ef81-11e6-a9f7-005056a66c27.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'kubernetes.pod_name:%22hogajama-180-cfc6f%22%20AND%20kubernetes.namespace_name:%2257-hogarama%22')),sort:!('@timestamp',desc))

**Comment by ErhardSiegl** [comment]
When I the link, I get:
`Discover: [security_exception] no permissions for indices:data/read/msearch`
When I select the Hogarama project on the left side, it works.

**Comment by hwirnsberger** [comment]
@steirer2 close it?

**Comment by ErhardSiegl** [comment]
Timed Out :-) Reopen if needed.
