### ISSUE TITLE
Rewrite UI for desktop Browsers

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#72]
First scatch by @Montecito :

![2017-08-25_hogarama_mobileoptimization](https://user-images.githubusercontent.com/1809686/29958688-48012b2e-8ef4-11e7-8933-d1b97ffba7fa.png)

- [x] The QR code should be a pop up where we can zoom a lot.
- [x] The Tiny Url should be an environment variable. For the presentation a second stage will get deployed, so a second tiny url is needed. The Tiny Url should be below the QR code.
- [x] The contrast for the horizontal chart bands is very bad. It was tried to fix it in hogajama-charts.html which isnt working.
- [x] display seconds 
- [x]  set correct timezone for fluentd container.

**Comment by Montecito** [comment]
All functional requests are now implemented.
What is left is the eye candy ;-)
