### ISSUE TITLE
Loadtest JMeter

### ISSUE THREAD

**Issue by hwirnsberger** [Gepardec/Hogarama#73]
At 1024 Tage Gepardec there will be around 100 visitors.
So our application should be able to handle 100 rest calls every 3 seconds.

**Comment by awagenhoffer** [comment]
It takes too long. There are only two strings. (collection.distinct("sensorName")) 
![sensors](https://user-images.githubusercontent.com/17886507/30326579-3e1a849c-97c9-11e7-99b5-fc7cbce3758d.png)
Proposed solutions: 
-Create a collection for the sensorName (Fluentd configurations)
-Cache (Quick solution)

**Comment by awagenhoffer** [comment]
After I`ve started 100 "User" in JMeter. Then I`ve opened my browser. 
![101user](https://user-images.githubusercontent.com/17886507/30327320-e5ae3206-97cb-11e7-99bd-58409a8b27e8.png)

**Comment by awagenhoffer** [comment]
Scale up have worked

**Comment by ErhardSiegl** [comment]
Considering the time constraint I would prefer the quick solution.

**Comment by awagenhoffer** [comment]
The result after optimization:
![optimiert](https://user-images.githubusercontent.com/17886507/30415297-c55080a6-9927-11e7-8e9e-f6b055134354.png)
Thread Group:
Number of Threads(users): 100
Ramp-Up Period(in seconds): 3
Loop Count: 100
