### ISSUE TITLE
Rules for watering plants

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#77]
**As user of Hogarama I want preconfigured and adaptable rules to regulate the pump for plants with different needs for water (rose and cactus) in order to enjoy all of them for more than one week.**

### Acceptance Criteria

- [ ] There is a flexible rules-system that implements the logic for watering.
- [ ] The rules can be adapted (to a certain degree) without changing and committing code.

### Implementation options:
The logic is implemented in a rules engine (JBoss Drooles) implemented in a separate container (microservice). JBoss BRMS could be an option, maybe Drooles with Spring Boot is good enough. Simple adjustments should be possible for the user without redeployment.

**Comment by sjutz** [comment]
How to run JBoss BRMS on openshift: https://developers.redhat.com/blog/2016/10/05/micro-rules-on-openshift-the-coolstore-just-became-even-cooler/

**Comment by hwirnsberger** [comment]
@ErhardSiegl the story is like an epic, please create stories :-D

**Comment by ErhardSiegl** [comment]
Well, right now its not an epic, but a drama! My cacti drown while my roses starve ;-)
However, if you think the issue is too big, we could start with some hardcoded rules which then are implemented by drools and then externalized in Red Hat Decision Manager (the new name for BRMS)
The development-team should say which direction it wants to go with the implementation of this story/epic/drama. Then we can define smaller steps.

**Comment by ErhardSiegl** [comment]
Right now we have a simple rules (if average within timeframe drops under a certain threshold water for time) but thy can't be changed without recompile. I propose to store the values in Mongo, then we can change them with Robo 3T.
