### ISSUE TITLE
Ansible for hogarama host configuration

### ISSUE THREAD

**Issue by cchet** [Gepardec/Hogarama#78]
I think instead of having a doc with endless linux shell commands, we could provide an ansible configuration for the developers, which setups the host as the current branch needs it to be.

I have already such an ansible configuration for cdk, s2i and oc for my workstation, which is able to perform an clean installation of cdk, s2i and oc.

The only thing the user has to do, is to download the cdk first, because it requires a login before a download.

**Comment by cchet** [comment]
This my fork where I work on:
https://github.com/cchet-gepardec/Hogarama/tree/ansible_config

**Comment by cchet** [comment]
A problem seems to be that only one minishift VM can be registered, which means if a developer has already a minishift VM registered, he needs to delete this VM (minishift delete) and then start the Hogarama provided one and visa versa if he wants to use his minishift instance again. 

Maybe we should support two options, one Hogarama setup with minishift and second Hogarama setup which expects an already setup minishift cluster.

**Comment by cchet** [comment]
I think now that a host will most likely not be able to provide enough resources to run openshift properly on the host. During the development on the branc *OPENSHIFT_JENKINS_PIPELINES* showed that the implemented pipelines cannot be run in parallel, because my laptop with 16GB RAM is not able of handling it.

Therefore I would prefer to use a cloud based openshift instance for demo purposes.

**Comment by ErhardSiegl** [comment]
Close it?
