### ISSUE TITLE
Discuss split Hogarama apps to separate repositories

### ISSUE THREAD

**Issue by cchet** [Gepardec/Hogarama#83]
Therefore that we want to show how to work with micro services in openshift, maybe we should split the apps to separate repositories, which provide their own source, doc and build configuration. 
We could bundle the apps repositories in a Github Organisation called 'Hogarama'.

Now the same repository is checked out and the builds are performed on the a specific app within this repository.

**Comment by AdrianFarmadin** [comment]
Maybe this can help: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by cchet** [comment]
I would prefer to have the hogarama cotnained applications to be independent in a way, that we do not have to trick with submodules and that we can manage the applications in their own repositories as microservice are supposed to be. Each appliaction should have their own repository, build, test, openshift templates, or what so ever.

**Comment by hwirnsberger** [comment]
i agree with cchet, the project did grow and the structure isnt that pretty. it would be a good opportunity for cleanup an refactoring
