### ISSUE TITLE
Integrate Quality Metrics (e.g. Test Coverage)

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#89]
As developer I want to have an overview about quality metrics in the project in order to improve quality and have fewer bugs to fix.

### Acceptance criteria
- [ ] There is a web page showing Hogarama quality metrics. It is updated on regular intervals.
- [ ] Documentations describes entry to configuration and critical installation steps in the wiki

 Integrate a tool like Sonar into the build

**Comment by cchet** [comment]
Where and who will build Hogarama in the future ?
There are jenkins plugins to report build status and test coverage/executions and results on github repositories.

**Comment by Montecito** [comment]
I have integrated hogajama in Travis CI:
https://travis-ci.org/Gepardec/Hogarama
and configured a sonar scan for it:
https://sonarcloud.io/dashboard?id=com.gepardec.hogajama%3Ahogajama

Is this sufficient?

**Comment by hwirnsberger** [comment]
Yes we will work with travis CI and sonar cloud.

For integration tests there will be a new issue.

**Comment by ErhardSiegl** [comment]
@Montecito Is this documented somewhere else?
