### ISSUE TITLE
Discuss docker image repository for Hogarama images

### ISSUE THREAD

**Issue by cchet** [Gepardec/Hogarama#93]
I have created an account on docker hub, which holds the slave images for the Jenkins builds.
https://hub.docker.com/u/gdhet/

Maybe we should create an own account on docker hub for Hogarama, or we should move the images to the Gepardec docker hub account.

**Comment by AdrianFarmadin** [comment]
The organization account on DockerHub for gepardec is already created. https://hub.docker.com/u/gepardec/   (Joined November 2016)

**Comment by cchet** [comment]
Good, than we should start using it :)

**Comment by hwirnsberger** [comment]
openshift has its own repository, why host it on dockerhub?

**Comment by ErhardSiegl** [comment]
@cchet is this answered?
