### ISSUE TITLE
Discuss implementation of Hogarama backups

### ISSUE THREAD

**Issue by cchet** [Gepardec/Hogarama#94]
We should discuss a implementation of the Hogarama infrastructure and the Hogarama build infrastructure (nexus-data directory, which holds downloaded maven artifacts)

**Comment by ErhardSiegl** [comment]
I don't see the connection between the issue description (build infrastructure) and backups. What should be backed up?

**Comment by cchet** [comment]
This ticket is for discussing a backup schema for the Hogarama build infrastructure. Backup of jenkins, nexus data or whatever is part of the build infrastructure. If we don't need backups, then this ticket is obsolete.

**Comment by ErhardSiegl** [comment]
There shouldn't be anything in the build infrastructure that can't be recreated from versioned source in Git or is so unimportant that it doesn't matter loosing it.
So right now I don't see the need for backups.

**Comment by hwirnsberger** [comment]
close it?
