### ISSUE TITLE
Develop issue writing guideline

### ISSUE THREAD

**Issue by b0x1** [Gepardec/Hogarama#96]
cf https://wiredcraft.com/blog/how-we-write-our-github-issues/
Create a template: https://github.com/blog/2111-issue-and-pull-request-templates

**DoD:**

- [ ] The guideline is documented in Gepardec Box.

**Comment by hwirnsberger** [comment]
Issue should be written as userstories. a template was added. closing this issue because it got added to gepardecbox github project
