### ISSUE TITLE
Set up regular Retrospectives

### ISSUE THREAD

**Issue by b0x1** [Gepardec/Hogarama#98]
We should have regular retrospectives, e.g. every two months, to discuss past achievements and future goals together.

**DoD**

- [ ] Issues and documentation from the 1st regular meeting.
- [ ] Issues and documentation from the 2nd regular meeting.
- [ ] Issues and documentation from the 3rd regular meeting.
- [ ] Issues and documentation from the 4th regular meeting.

**Comment by WernerGepardec** [comment]
Know-how should go into the Gepardec-Box.

**Comment by hwirnsberger** [comment]
Retros are part of scrum. so for now i would like to try to have a retro each sprint.
