### ISSUE TITLE
Define process to integrate scrum for hogarama

### ISSUE THREAD

**Issue by b0x1** [Gepardec/Hogarama#99]
To get started with Scrum in Hogarama we first have to define how to integrate it.
Because we normally only work on friday for hogarama it is a challenge to integrate it.

Do we need a PO?
Do we need a Scrum Master?
How long is a Sprint?
Do we need all Meetings? (Sprint Planning, Standup, Sprint Review, Sprint Retro)
How often do we change the roles (PO / Master)?

**DoD**
- [x] There is a way to integrate Scrum in hogarama and it is documented
- [x] All needed roles are assigned
- [x] The roles know what to do

**Comment by WernerGepardec** [comment]
Know-how should go into the Gepardec-Box.

**Comment by hwirnsberger** [comment]
Documentation in internal wiki
